version: "3.9"

services:
  db:
    image: postgres:16
    container_name: giapha-postgres
    environment:
      POSTGRES_DB: giapha
      POSTGRES_USER: giapha_user
      POSTGRES_PASSWORD: giapha_pass
    ports:
      - "5432:5432"
    volumes:
      - giapha_db_data:/var/lib/postgresql/data

volumes:
  giapha_db_data:

